### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by popltree2** [arcreative/homebridge-xbox-one#1]
I'm getting the following error when trying to enact the toggle to power on my Xbox One.

[XboxOne] Sending on command to 'XboxOne'...

buffer.js:491
      length += buf.length;
                   ^
TypeError: Cannot read property 'length' of undefined
    at Function.Buffer.concat (buffer.js:491:20)
    at Xbox.powerOn (/usr/local/lib/node_modules/homebridge-xbox-one/node_modules/xbox-on/index.js:17:24)
    at null._onTimeout (/usr/local/lib/node_modules/homebridge-xbox-one/index.js:28:19)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

**Comment by arcreative** [comment]
What node version are you using?  This is more of an issue for arcreative/xbox-on, but we can handle it here

**Comment by arcreative** [comment]
For reference, sounds like `0.10.25`, and can confirm the issue.

**Comment by arcreative** [comment]
Fixed this over at arcreative/xbox-on in version `0.0.6`.  Doing `npm install -g homebridge-xbox-one` should fix it for you, thanks!
